### ISSUE TITLE
Please consider including a license

### ISSUE THREAD

**Issue by cscharf** [hazzik/mono.reflection#2]
Currently there is no license for acceptable use, distribution or derivative works for this code and package, which is currently distributed via NuGet and GitHub; however without a license has no acceptable fair use: see: https://choosealicense.com/no-permission/.

Please consider choosing and including a license for this repository/project.

**Comment by hazzik** [comment]
There is a license. It is included into the repository and nuget.

**Comment by hazzik** [comment]
The license is MIT. The license is included at the header of every .cs file and there is a link to license on the nuget package.
